#!/bin/bash

#       _____      _                     
#      / ____|    | |                    
#     | |     ___ | | ___  _ __ ___  ___ 
#     | |    / _ \| |/ _ \| '__/ _ \/ __|
#     | |___| (_) | | (_) | | |  __/\__ \
#      \_____\___/|_|\___/|_|  \___||___/
#                                        
#                                        

GREEN="\033[1;32m"
LRED="\033[0;31m"
RED="\033[1;31m"
YELLOW="\033[1;33m"
BLUE="\033[1;36m"
GRAY="\033[1;37m"
RESET="\033[0m"

#     __      __        _       _     _           
#     \ \    / /       (_)     | |   | |          
#      \ \  / /_ _ _ __ _  __ _| |__ | | ___  ___ 
#       \ \/ / _` | '__| |/ _` | '_ \| |/ _ \/ __|
#        \  / (_| | |  | | (_| | |_) | |  __/\__ \
#         \/ \__,_|_|  |_|\__,_|_.__/|_|\___||___/
#                                                 
#                                                 

ZONE_ID=''
API_TOKEN=''
CNAME=''

#       _____  __      _ _             
#      / ____|/_/     | (_)            
#     | |     ___   __| |_  __ _  ___  
#     | |    / _ \ / _` | |/ _` |/ _ \ 
#     | |___| (_) | (_| | | (_| | (_) |
#      \_____\___/ \__,_|_|\__, |\___/ 
#                           __/ |      
#                          |___/       



ctl_c(){
  echo -e "\n${RED}\n[!] Saliendo...\n${RESET}" && sleep 1
  clear
  exit 0
}

trap ctl_c INT

while true; do
  clear
  echo '          _____                    _____                    _____          
         /\    \                  /\    \                  /\    \         
        /::\    \                /::\____\                /::\    \        
       /::::\    \              /::::|   |               /::::\    \       
      /::::::\    \            /:::::|   |              /::::::\    \      
     /:::/\:::\    \          /::::::|   |             /:::/\:::\    \     
    /:::/  \:::\    \        /:::/|::|   |            /:::/__\:::\    \    
   /:::/    \:::\    \      /:::/ |::|   |            \:::\   \:::\    \   
  /:::/    / \:::\    \    /:::/  |::|   | _____    ___\:::\   \:::\    \  
 /:::/    /   \:::\ ___\  /:::/   |::|   |/\    \  /\   \:::\   \:::\    \ 
/:::/____/     \:::|    |/:: /    |::|   /::\____\/::\   \:::\   \:::\____\
\:::\    \     /:::|____|\::/    /|::|  /:::/    /\:::\   \:::\   \::/    /
 \:::\    \   /:::/    /  \/____/ |::| /:::/    /  \:::\   \:::\   \/____/ 
  \:::\    \ /:::/    /           |::|/:::/    /    \:::\   \:::\    \     
   \:::\    /:::/    /            |::::::/    /      \:::\   \:::\____\    
    \:::\  /:::/    /             |:::::/    /        \:::\  /:::/    /    
     \:::\/:::/    /              |::::/    /          \:::\/:::/    /     
      \::::::/    /               /:::/    /            \::::::/    /      
       \::::/    /               /:::/    /              \::::/    /       
        \::/____/                \::/    /                \::/    /        
         ~~                       \/____/                  \/____/         '



    # Menú
    echo "[1] Consultar mis dominios"
    echo "[2] Agregar un subdominio"
    echo "[3] Eliminar un subdominio"
    echo "[4] Cambiar mis variables"
    echo "[5] Salir"
    echo -e "\n"
    read -n1 -s -p "¿Qué desea hacer? " option;
    echo -e "\n"
    
  
  if [[ ! $option =~ ^[1-5]$ ]]; then
    echo -e "${YELLOW}Eliga una opción valida.${RESET}" && sleep 1
  fi;
  
  case $option in
    
    1)
      response=$(curl -s -X GET "https://api.cloudflare.com/client/v4/zones/$ZONE_ID/dns_records" -H "Authorization: Bearer $API_TOKEN" -H "Content-Type: application/json")
      echo -e "\n"

      success=$(echo "$response" | jq -r '.success')
      if [  "$success" != "true" ]; then 
        echo -e "${RED}[!] Ha ocurrido un error al establecer la conexión con el servidor, revise sus parámetros.${RESET}" && sleep 3
        continue
      fi

      lista=$(echo "$response" | jq -r '.result[] | "\(.name) \(.id)"')

      echo '
        _           _                 _       _           
  /\/\ (_)___    __| | ___  _ __ ___ (_)_ __ (_) ___  ___ 
 /    \| / __|  / _` |/ _ \| '\''_ '\'' _ \| | '\''_ \| |/ _ \/ __|
/ /\/\ \ \__ \ | (_| | (_) | | | | | | | | | | (_) \__ \
\/    \/_|___/  \__,_|\___/|_| |_| |_|_|_| |_|_|\___/|___/
'

      while read -r nombre id; do
        echo -e "[*] ${BLUE}$nombre${RESET}"
      done <<< "$lista"
      echo -e "\n"
      read -p "Presione Enter para volver al menú principal..."
    ;;


    2)
      read -p "Indique el subdominio a agregar: " subdominio
      
      while true; do
        read -n1 -p "Con proxy : Sí(Y) | No(N): " proxy
        echo -e "\n"
        case "$proxy" in
          y|Y|yes|Yes)
            proxied="true"
            break
          ;;
          n|N|no|No)
            proxied="false"
            break
          ;;
          *) 
            echo -e "${RED}[!] Valor inválido${RESET}" && sleep 2
            continue
          ;;
        esac
      done

      response=$(curl -s -X POST "https://api.cloudflare.com/client/v4/zones/$ZONE_ID/dns_records" \
      -H "Authorization: Bearer $API_TOKEN" \
      -H "Content-Type: application/json" \
      --data "{
          \"type\": \"CNAME\",
          \"name\": \"$subdominio\",
          \"content\": \"$CNAME\",
          \"ttl\": 3600,
          \"proxied\": $proxied
      }")
      
      if echo $response | jq -e '.success' >/dev/null; then
        echo -e "${GREEN}[] Se ha agregado el dominio $subdominio correctamente.${RESET}" && sleep 3
        continue
      elif echo $response | jq -e '.errors[] | select(.code == 81053)' >/dev/null; then
        echo -e "${YELLOW}[!] El dominio $subdominio ya existe.${RESET}" && sleep 3
        continue
      elif echo $response | jq -e '.errors[] | select(.code == 9000)' >/dev/null; then
        echo -e "${RED}[!] El dominio $subdominio no es un nombre válido.${RESET}" && sleep 3
        continue
      else
        echo -e "${RED}[x] No se ha podido agregar el subdominio $subdominio ${RESET}" && sleep 5
      fi;
  
    ;;
  
    3)
      lista=$(curl -s -X GET "https://api.cloudflare.com/client/v4/zones/$ZONE_ID/dns_records?type=CNAME" -H "Authorization: Bearer $API_TOKEN" -H "Content-Type: application/json" | jq -r '.result[] | "\(.name) \(.id)"')
            echo '
        _           _                 _       _           
  /\/\ (_)___    __| | ___  _ __ ___ (_)_ __ (_) ___  ___ 
 /    \| / __|  / _` |/ _ \| '\''_ '\'' _ \| | '\''_ \| |/ _ \/ __|
/ /\/\ \ \__ \ | (_| | (_) | | | | | | | | | | (_) \__ \
\/    \/_|___/  \__,_|\___/|_| |_| |_|_|_| |_|_|\___/|___/
'
      contador=1
      declare -A dom
      while read -r nombre id;do
        echo -e "[$contador] ${BLUE}$nombre${RESET}"
        dom[$contador]="$nombre $id"
        contador=$((contador + 1))
      done <<< "$lista"
      echo -e "[$contador] ${GRAY}Salir${RESET}"
      echo -e "\n"
  
      read -s -n1 -p "Seleccione el número del dominio a eliminar: " subdominio
      
      subdom=${dom[$subdominio]}
      nombre=$(echo $subdom | awk '{ print $1 }')
      id=$(echo $subdom | awk '{ print $2 }')
      
      total=$(echo "$lista" | wc -l)
  
      if [[ "$subdominio" < 1 || "$subdominio" > "$(($total +1))" ]]; then
        echo -e "${RED}Número inválido${RESET}"
        continue
      elif [[ "$subdominio" == "$(($total +1))" ]]; then
        continue
      fi
      
      echo -e "\n"
      echo "Has seleccionado el dominio: $nombre." 
      echo -e "${YELLOW}󰀦 ¿Está seguro que desea eliminiarlo? Sí (Y) | No (N)${RESET}"
  
      while true; do
        read -n1 -s -r res
        case "$res" in
          y|Y)
            echo "Eliminando $nombre..."
            delete=$(curl -s -X DELETE "https://api.cloudflare.com/client/v4/zones/$ZONE_ID/dns_records/$id" \
  -H "Authorization: Bearer $API_TOKEN" \
  -H "Content-Type: application/json" | jq)
  
            if echo "$delete" | jq -e '.success' >/dev/null; then
              echo -e "${GREEN}[] Dominio $nombre eliminado correctamente.${RESET}"
              sleep 3
              break
            elif echo "$delete" | jq -e '.81044' >/dev/null; then
              echo "[!] El dominio $nombre no existe.";
            else
              echo "[x] No se ha podido eliminar $nombre.";
            fi;
  
            break
          ;;
      
          n|N)
            echo -e "${LRED}[!] Acción anulada${RESET}"
            sleep 2
            break
            
          ;;
  
          *)
            echo "Por favor, introduzca una opción válida (y/n)."
          ;;
        esac
      done
  
      ;;
    
    4)
      while true; do
        options=("Modificar ZONE ID" "Modificar API TOKEN" "Modificar CNAME")
        contador=1

        for option in "${options[@]}"; do
          echo -e "[$contador] ${BLUE}$option${RESET}"
          contador=$((contador + 1))
        done
        echo -e "${GRAY}[$contador] Salir${RESET}\n"
        read -n1 -s -p "Seleccione una opción: " opcion
        
        case "$opcion" in
          1)
            echo -e "\n"
            read -s -r -p "Introduzca el nuevo ZONE ID (Presione Ctrl + C para cancelar): " new_zone
            sed -i "29s|^ZONE_ID='.*'|ZONE_ID='$new_zone'|" $0
            echo -e "\n${GREEN}[] La nueva zona ya está disponible.${RESET}" && sleep 2
            exec $0
          ;;


          2)
            echo -e "\n"
            read -s -r -p "Introduzca el nuevo token (Presione Ctrl + C para cancelar): " new_token
            sed -i "30s|^API_TOKEN='.*'|API_TOKEN='$new_token'|" $0
            echo -e "\n${GREEN}[] El nuevo token ya está disponible.${RESET}" && sleep 2
            exec $0
          ;;

          3)
            echo -e "\n"
            read -r -p "Introduzca el nuevo CNAME (Actual: $CNAME): " new_cname
            sed -i "31s|^CNAME='.*'|CNAME='$new_cname'|" $0
            echo -e "${GREEN}[] El nuevo CNAME ya está disponible.${RESET}" && sleep 2
            exec $0
          ;;
          
          4)
            break
          ;;
          *)
            echo -e "\n\n${RED}[!] Introduzca una opción válida.${RESET}\n" && sleep 2
            continue


          ;;
        esac
     # read -s -r -p "Introduzca el nuevo token" n_token
     # sed -i "27s|^API_TOKEN='.*'|API_TOKEN='$n_token'|" $0
     # read -p "¡Listo! Pulse Enter para continuar..."
     # exec $0
      done
    ;;



    5)
      echo "Saliendo..."
      clear
      exit 0
    ;;
  esac
done
  
